#!/usr/bin/env python
import sys
import random

if __name__ == '__main__':
	sys.stdout.write("executed dlslfc-add %s"%sys.argv[1:])
	if random.random()< 0.0001:
		sys.stderr.write("GONG!!!")
	sys.exit(0)
