#!/usr/bin/env python

# lfc-del-dir
# 11/05
# Author: Antonio Delgado Peris. CERN, LCG.

import lfc_del_dir
import sys


######################### SCRIPT ###########################

if __name__ == "__main__":
  sys.exit(lfc_del_dir.main(sys.argv[1:]))

